### ISSUE TITLE
"Unable to find the chromedriver executable"

### ISSUE THREAD

**Issue by nhoizey** [desktoppr/wbench#22]
I installed wbench and chromedriver as mentioned, but I keep getting this error:

`/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.33.0/lib/selenium/webdriver/chrome/service.rb:20:in `executable_path': Unable to find the chromedriver executable. Please download the server from http://code.google.com/p/chromedriver/downloads/list and place it somewhere on your PATH. More info at http://code.google.com/p/selenium/wiki/ChromeDriver. (Selenium::WebDriver::Error::WebDriverError)`

I can run `$ chromedriver`from anywhere, so I'm sure it is in the PATH.

Here is the full error message:

```
$ wbench http://gasteroprod.com/
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.33.0/lib/selenium/webdriver/chrome/service.rb:20:in `executable_path': Unable to find the chromedriver executable. Please download the server from http://code.google.com/p/chromedriver/downloads/list and place it somewhere on your PATH. More info at http://code.google.com/p/selenium/wiki/ChromeDriver. (Selenium::WebDriver::Error::WebDriverError)
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.33.0/lib/selenium/webdriver/chrome/service.rb:33:in `default_service'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.33.0/lib/selenium/webdriver/chrome/bridge.rb:14:in `initialize'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.33.0/lib/selenium/webdriver/common/driver.rb:37:in `new'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.33.0/lib/selenium/webdriver/common/driver.rb:37:in `for'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.33.0/lib/selenium/webdriver.rb:67:in `for'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/capybara-2.1.0/lib/capybara/selenium/driver.rb:11:in `browser'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/capybara-2.1.0/lib/capybara/selenium/driver.rb:43:in `visit'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/capybara-2.1.0/lib/capybara/session.rb:193:in `visit'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/wbench-0.3.7/lib/wbench/browser.rb:23:in `visit'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/wbench-0.3.7/lib/wbench/benchmark.rb:20:in `block (2 levels) in run'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/wbench-0.3.7/lib/wbench/benchmark.rb:18:in `times'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/wbench-0.3.7/lib/wbench/benchmark.rb:18:in `block in run'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/wbench-0.3.7/lib/wbench/benchmark.rb:17:in `tap'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/wbench-0.3.7/lib/wbench/benchmark.rb:17:in `run'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/wbench-0.3.7/lib/wbench/benchmark.rb:4:in `run'
    from /usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/wbench-0.3.7/bin/wbench:32:in `<top (required)>'
    from /usr/local/opt/ruby/bin/wbench:23:in `load'
    from /usr/local/opt/ruby/bin/wbench:23:in `<main>'
```

**Comment by reach2jeyan** [comment]
@mariovisic Can you let me know where do I place it in windows machine? I am currently using ruby program to automate test cases, and want to use chrome browser. I had it working with I had the `chromedriver` placed in the `lib` folder of `ruby`. After I had to format my system, I am again facing this error and placing this in `lib` now doesnt work.

PFB the error.

```
`C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/common/service.rb:59:in `binary_path':  Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. (Selenium::WebDriver::Error::WebDriverError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/common/service.rb:49:in `initialize'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/chrome/bridge.rb:35:in `new'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/chrome/bridge.rb:35:in `initialize'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/common/driver.rb:61:in `new'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/common/driver.rb:61:in `for'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver.rb:82:in `for'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/browser.rb:46:in `initialize'
        from C:/Users/Mrityunjeyan/Documents/GitHub/Simpleprograms/webautomation.rb:7:in `new'
        from C:/Users/Mrityunjeyan/Documents/GitHub/Simpleprograms/webautomation.rb:7:in `<main>'`
```

**Comment by reach2jeyan** [comment]
@mariovisic Got it working!
