### ISSUE TITLE
timing_hash.rb:8:in `each': comparison of Fixnum with String failed (ArgumentError)

### ISSUE THREAD

**Issue by ITspirit** [desktoppr/wbench#31]
I've just installed wbench on Ubuntu 12, but i recieve this error:

wbench -b firefox https://www.desktoppr.co/

/var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/timing_hash.rb:8:in `each': comparison of Fixnum with String failed (ArgumentError)
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/timing_hash.rb:8:in`min_by'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/timing_hash.rb:8:in `initialize'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/timings/browser.rb:9:in`new'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/timings/browser.rb:9:in `result'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/benchmark.rb:32:in`browser_results'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/benchmark.rb:20:in `block (3 levels) in run'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/browser.rb:26:in`visit'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/benchmark.rb:20:in `block (2 levels) in run'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/benchmark.rb:18:in`times'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/benchmark.rb:18:in `block in run'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/benchmark.rb:17:in`tap'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/benchmark.rb:17:in `run'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/lib/wbench/benchmark.rb:4:in`run'
    from /var/lib/gems/1.9.1/gems/wbench-0.4.0/bin/wbench:39:in `<top (required)>'
    from /usr/local/bin/wbench:19:in`load'
    from /usr/local/bin/wbench:19:in `<main>'

any ideas?

**Comment by toshiyuki-hasegawa-TL** [comment]
Hi Thank you for a great product!

But I receive this error since July 23nd, 2015 (JP time).
It always error occurs.
It did not receive an error until July 22, 2015 (JP time).

Mac : OS X Yosemite 10.10.4
Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
Chrome : 44.0.2403.107 (64-bit)

```bash
$ ./bin/wbench -l 1 http://www.google.com
/Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/timing_hash.rb:8:in `each': comparison of Hash with 1438133594940 failed (ArgumentError)
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/timing_hash.rb:8:in `min_by'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/timing_hash.rb:8:in `initialize'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/timings/browser.rb:9:in `new'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/timings/browser.rb:9:in `result'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/benchmark.rb:32:in `browser_results'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/benchmark.rb:20:in `block (3 levels) in run'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/browser.rb:34:in `visit'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/benchmark.rb:20:in `block (2 levels) in run'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/benchmark.rb:18:in `times'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/benchmark.rb:18:in `block in run'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/benchmark.rb:17:in `tap'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/benchmark.rb:17:in `run'
        from /Users/toshiyuki_hasegawa/workspace/wbench/lib/wbench/benchmark.rb:4:in `run'
        from ./bin/wbench:43:in `<main>'
```

Could you tell me if you have an idea that can be resolved?
